### ISSUE TITLE
TWINT still not working - related to issue #354

### ISSUE THREAD

**Issue by Janine65** [schoero/SwissQRBill#356]
av1 and av2 are correct filled by RaiseNow.com, but the QRBill is not correct. av1 and av2 are printed, the creator and deptor part are on the third page.
The QRCode is correct, means it can be payed by TWINT App.
[AMC-Mitgliederbeitrag-2022-118.pdf](https://github.com/schoero/SwissQRBill/files/7613825/AMC-Mitgliederbeitrag-2022-118.pdf)
Attached the styleguide of TWINT QR-Billing
[TWINT QR-Rechnung - Styleguide .pdf](https://github.com/schoero/SwissQRBill/files/7613836/TWINT.QR-Rechnung.-.Styleguide.pdf)
and a Payload example:
[TWINT QR-Rechnung - Payload Beispiel.txt](https://github.com/schoero/SwissQRBill/files/7613843/TWINT.QR-Rechnung.-.Payload.Beispiel.txt)

**Comment by schoero** [comment]
Thank you for reporting this again. I never used the alternative schemes and did not recognise that they were broken.

I have released a beta version which should definitely fix the rendering issues. You can install it using

```sh
npm i swissqrbill@beta
```

With the new version, the generated QR-Bill should look something like this, which should comply with the specifications:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/42278642/143784634-7a9c81b3-c4e6-48c2-b436-951ee640e8e1.png">

Can you test the new version and confirm that the alternative schemes are now working properly before I release a new stable version?

**Comment by Janine65** [comment]
Hi
I can test it next Weekend an will give you feedback asap. 
One correction: the av1 and av2 should not be printed at the end. 
cheers
Janine

**Comment by schoero** [comment]
> One correction: the av1 and av2 should not be printed at the end.

Are you sure about that? I could not find any reference that states this (other than the images in the styleguide that you have referred to, that indicate this). And generally all data, that is present in the QR-Code should also be printed on the QR-Bill.

Other than that, i have found an implementation that renders it exactly like in my previous image of the new version: [qr-rechnung.net](https://qr-rechnung.net/#/b,en,SPC,0200,1,CH5204835012345671000,S,Max%20Muster%20%26%20S%C3%B6hne,Musterstrasse,123,8000,Seldwyla,CH,,,,,,,,1949.75,CHF,S,Sarah%20Beispiel,Musterstrasse,1,8000,Seldwyla,CH,NON,,Auftrag%20vom%2029.11.2021,EPD,%2F%2FS1%2F11%2F211129%2F30%2F102673386%2F31%2F211129%2F32%2F7.7%2F40%2F0%3A30,twint%2Flight%2F02%3A7f136ad5a9a94a1785c8be3d9a1a26bf%23bb43eaa1f9e9126c709dc66adc12bc0b3906530b%23,rn%2Ftwint%2Fa~5vkrFtpDRN6bWUdZpS4LOw~s~uORhJ5J4Symv5K4LaeuzKA%2Frn)

**Comment by Janine65** [comment]
No. I'm not sure. I will test it next weekend and send it as a test to RaiseNow for verification.

**Comment by schoero** [comment]
Alright, thank you 👍

**Comment by Janine65** [comment]
It looks good now except one thing: There should be the TWINT boarder at the top of the qr-billing...
![image](https://user-images.githubusercontent.com/54989368/144710930-768f8966-346d-4e01-89ab-079d19db6d97.png)
So I have to add this, correct? No problem, I have it done, but it must be documented, that this boarder has to be done.

**Comment by schoero** [comment]
Thank you for testing.

The TWINT banner is not a requirement, neither by the QR-Bill specifications, nor by TWINT.
As you can read in the first paragraph of the style guide you referenced, it is simply a recommendation to draw attention to the fact that this specific QR bill can be paid with TWINT.

> Um Ihre Unterstützer und Mitglieder darauf aufmerksam zu machen, dass die 
QR-Rechnung auch mit der TWINT App gescannt werden kann, empfehlen wir, 
unsere TWINT Banner in Ihre Rechnungsvorlage aufzunehmen.

Therefore, I don't think that it has to be documented in this library.

I think the TWINT banner is a good thing and I would definitely include it in my QR-Bills if they where TWINT compatible, but I am not sure if such a functionality should be added to this library, since it is not a part of the QR-Bill specifications.

I'm gonna go ahead and release a new version with these fixes this weekend. I may decide to integrate the banner for a future version.

**Comment by schoero** [comment]
SwissQRBill v3.1.3 that fixes this issue is now released on npm.
