### ISSUE TITLE
Embedding anything other than Vector Paths

### ISSUE THREAD

**Issue by cbrasser** [schoero/SwissQRBill#366]
Hi there, thank you for this awesome library! Just a quick question: There is currently no option to embed anything other than Vector paths in the final pdf, right?

How would you go about embedding png images or other pdf files into the final pdf?

**Comment by schoero** [comment]
Hi

It is possible to add other images than vector paths. Since this library is based on PDFKit, there are many more methods available than those documented in [doc/api.md](https://github.com/schoero/SwissQRBill/blob/master/doc/api.md)
Take a look at the [PDFKit documentation](http://pdfkit.org/docs/images.html) for further information.

```ts
pdf.image("path/to/image.jpg", 20, 20, { width: 100, height: 100 });
```
