### ISSUE TITLE
Expose a function to only get the QRCode with the swiss cross

### ISSUE THREAD

**Issue by Jan-Vermeulen** [schoero/SwissQRBill#382]
Greetings !
Could you add the possibility to generate an SVG with the QRCode only ?
I would need to have that to display it in a web page without all the other informations  😊

**Comment by schoero** [comment]
I have seen other libraries in other programming languages support this, and my personal opinion is that this could have legitimate applications in real life and I think the recognition value as a QR-Bill is still provided by the swiss cross in the center.

But I don't want to add this as a feature, because I am pretty sure that this doesn't comply with the specifications and violates the [design guidelines](https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf) of the QR-Bill.

However, it may already be possible in a hacky way: https://github.com/schoero/SwissQRBill/discussions/374, [jsfiddle](https://jsfiddle.net/sw3nv08L/)

Let me know if that works for you.

**Comment by Jan-Vermeulen** [comment]
Thanks for the quick answer !

It's working perfectly 💪
