### ISSUE TITLE
Invoice with different currencies

### ISSUE THREAD

**Issue by krava77** [schoero/SwissQRBill#395]
Hello.
Is it possible to create pdf invoices with different currencies (e.g. USD, GBP etc.)?
At the moment I have got an error, but sometimes is necessary to display an invoice for customers in different currencies without QR code.
Thank you!

**Comment by schoero** [comment]
The error is intentional because the Swiss QR Bill only supports "CHF" and "EUR". This is an official limitation of the Swiss QR Bill, you can search for _currency_ in the [official specifications](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-en.pdf) to verify that.

If we would allow other currencies anyway, this would probably lead to errors when scanning the QR Bill.

**Comment by krava77** [comment]
Thank you for the answer. I saw it in the source code.
Is it possible to allow other currencies without a QR code? For example, if the currency is not  "CHF" and "EUR" QR code is not appear.

**Comment by schoero** [comment]
This is something I would rather not implement. If it looks like a QR Bill, it should also behave like a QR Bill.

In addition to that, leaving parts out also violates the [official design guidelines](https://www.paymentstandards.ch/dam/downloads/style-guide-en.pdf).

If the transaction has to be in a different currency, I suggest to create a custom Bill, that just includes the necessary payment information and not use the Swiss QR Bill at all.

If you just want to display the amount in another currency, you could display that above the payment part of the QR Bill and leave the actual payment part of the QR Bill in "CHF" or "EUR".

**Comment by schoero** [comment]
Closing as this does not comply with the specifications.
