### ISSUE TITLE
Additional Information is Not showing properly

### ISSUE THREAD

**Issue by Abhishek3058** [schoero/swissqrbill#416]
Hello Sir, I am Abhishek Modanwal and currently Using your library in my projects
and the main problem is when we scan qr code in normal scanner then it shows properly additional information and when it scans in payment app ,additional information is not showing,
plz update library 
![image](https://github.com/schoero/SwissQRBill/assets/81512918/4f26687b-40d6-4d8b-b19a-27ce7f807819)

this is data from demo image and image  provided by google 
and here i think due to EPD additional info is not shown 
also when i scanned some more qr code where EPD is not shown , is able to shown additional information

**Comment by schoero** [comment]
`EPD` is a mandatory field. It always has to be present and it always has to be in that exact location. You can search for `EPD` in the [specification](https://www.six-group.com/dam/download/banking-services/standardization/qr-bill/ig-qr-bill-v2.2-en.pdf) for verification.

Can you paste your QR-Bill into the [QR-Invoice validator](https://swiss-qr-invoice.org/validator/?lang=de). Does it report any errors or warnings? Maybe it is because other parts of the data are invalid.

Another explanation I can think of is that your payment app is meant to hide the `additional information` field, because this field is not designed to be human readable.

Does this make you unable to pay with the QR-Bill, or is the UI of the app just missing some information?

**Comment by schoero** [comment]
I assume that the problem has been resolved for you. Please reopen or create a new issue if you need further assistance.
